"""Collect ASF SAR metadata and export it as daily Parquet catalogs.

Public API (guaranteed to ``fetch-asf``, see ``AGENTS.md`` section 7)::

    from metadata_asf import search, extract, export
    from metadata_asf.profiles import get_profile
"""

from __future__ import annotations

try:  # ``_version.py`` is generated by hatch-vcs at build/install time.
    from metadata_asf._version import __version__
except ImportError:
    __version__: str = "0.0.0"

from metadata_asf import cli, config, export, extract, profiles, search
from metadata_asf.profiles import get_profile

__all__ = [
    "__version__",
    "cli",
    "config",
    "extract",
    "export",
    "get_profile",
    "profiles",
    "search",
]
